command: ['npm', 'run', 'start']
env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: LAKEBASE_ENDPOINT
    value: projects/gpu-hub/branches/production/endpoints/primary
  - name: PGHOST
    value: ep-old-water-d26susqc.database.us-east-1.cloud.databricks.com
  - name: PGDATABASE
    value: databricks_postgres
  - name: PGSSLMODE
    value: require
